---
title: "Fatty acids and ALS"
format: html
editor: visual
toc: true
toc_depth: 4
theme:
  light: flatly
  dark: darkly
toc-location: left
---

```{r}
#| message: false
#| warning: false
#| include: false
source("~/Documents/POP_ALS_2025_02_03/1_codes/lipids.R")
```

# Data description
## Comparison finnish / danish
### Covariates
```{r}
#| echo: false
#| message: false
#| warning: false
bdd %>%
  select("study", "sex", "marital_status_2cat", "smoking_2cat", "alcohol", "education", 
         "bmi", "cholesterol", "baseline_age", "diagnosis_age") %>%
  tbl_summary(by = "study") %>%
  bold_labels() %>%
  add_p()
```

### POPs
```{r}
#| echo: false
#| message: false
#| warning: false
bdd |> 
  select(sample, als, study, all_of(POPs), all_of(POPs_group)) |>
  pivot_longer(cols = c(-sample, -als, -study), names_to = "POPs", values_to = "Values") |>
  mutate(
    POPs =   fct_relevel(POPs, 
    "PCB_DL", "PCB_118", "PCB_156", "PCB_NDL", "PCB_4", "PCB_28",
    "PCB_52", "PCB_74", "PCB_99", "PCB_101", "PCB_138", "PCB_153",
    "PCB_170", "PCB_180", "PCB_183", "PCB_187", "OCP_HCB", "OCP_PeCB",
    "ΣDDT", "OCP_pp_DDE", "OCP_pp_DDT", "Σchlordane", "OCP_oxychlordane",
    "OCP_transnonachlor", "OCP_α_HCH", "OCP_β_HCH", "OCP_γ_HCH",
    "ΣPBDE", "PBDE_47", "PBDE_99", "PBDE_153"), 
    POPs = fct_rev(POPs)) |>
  arrange(POPs) |>
  ggplot() +
  aes(x = Values, y = POPs, fill = study) +
  geom_boxplot() +
  scale_fill_hue(direction = 1) +
  labs(
    x = "Serum concentration (pg/ml)",
    y = "POPs",
    fill = "Cohorts") +
  theme_lucid()

bdd |>
  filter(als == 0) |>
  select(study, all_of(POPs), all_of(POPs_group)) |>
  tbl_summary(by = "study") |>
  bold_labels() |>
  add_n()
```


