---
title: "Fatty acids and ALS"
format: html
editor: visual
toc: true
toc_depth: 4
theme:
  light: flatly
  dark: darkly
toc-location: left
---

```{r}
#| message: false
#| warning: false
#| include: false
source("~/Documents/POP_ALS_2025_02_03/1_codes/lipids in finland cohort.R")
```

# Data description
## Density plots 
```{r, fig.height=10, fig.width=10}
#| echo: false
#| message: false
#| warning: false
#| column: screen-inset-right

bdd_finnish |> 
  select(sample, all_of(fatty_acids)) |>
  pivot_longer(cols = -sample, names_to = "fattyacids", values_to = "values") |>
  ggplot() +
  aes(x = values) +
  geom_density(fill = "#112446") +
  theme_minimal() +
  facet_wrap(~fattyacids, scales = "free", ncol = 4)
```

## Boxplots
```{r, fig.height=10, fig.width=10}
#| echo: false
#| message: false
#| warning: false
#| column: screen-inset-right

bdd_finnish |> 
  select(sample, all_of(fatty_acids)) |>
  pivot_longer(cols = -sample, names_to = "fattyacids", values_to = "values") |>
  ggplot() +
  aes(x = "", y = values) +
  geom_boxplot(shape = "circle", fill = "#112446") +
  coord_flip() +
  theme_bw() +
  theme(axis.title = element_blank()) +
  facet_wrap(~fattyacids, scales = "free", ncol = 3L, nrow = 14L)

bdd_finnish |> select(sample, all_of(fatty_acids)) |>
  pivot_longer(cols = -sample, names_to = "fattyacids", values_to = "values") |>
  ggplot() +
  aes(x = values, y = fattyacids) +
  geom_boxplot(fill = "#112446") +
  theme_minimal()
```

## Distribution tables 
```{r, fig.height=10, fig.width=10}
#| echo: false
#| message: false
#| warning: false
#| column: screen-inset-right

descrip_num(data = bdd_finnish, vars = fatty_acids)
```

## Heatmap of correlation
```{r, fig.height=10, fig.width=10}
#| echo: false
#| message: false
#| warning: false
#| column: screen-inset-right

heatmap_fattyacids <- bdd_finnish |> select(all_of(fatty_acids))
heatmap_fattyacids <- cor(heatmap_fattyacids, 
                    use = "pairwise.complete.obs", 
                    method = "pearson")

corrplot(heatmap_fattyacids, 
         method = 'color', 
         type = "lower", 
         tl.col = 'black', 
         tl.srt = 45, 
         addCoef.col = "black",
         number.cex = 0.8,
         number.digits = 1,
         tl.cex = 1,
         col = rev(COL2(diverging = "RdYlBu")))

heatmap_cor_pairwise(fatty_acids, POPs, decimal = 1, data = bdd_finnish)
```

## Calcium (indicator of quality)
```{r}
#| echo: false
#| message: false
#| warning: false
boxplot(data = bdd_finnish, vars = c("S-Ca", "fS-Trigly", "fS-Kol"))
descrip_num(data = bdd_finnish, vars = c("S-Ca", "fS-Trigly", "fS-Kol"))
```

